name: media

services:
  media-deluge:
    container_name: media-deluge
    image: lscr.io/linuxserver/deluge:latest
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/data/downloads:/downloads
      - deluge_config:/config
    ports:
      - "8112:8112"
    networks:
      - media-network

  media-radarr:
    container_name: media-radarr
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/data/movies:/movies
      - /mnt/data/downloads:/downloads
      - radarr_config:/config
    ports:
      - "7878:7878"
    networks:
      - media-network

  media-sonarr:
    container_name: media-sonarr
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/data/tv:/tv
      - /mnt/data/downloads:/downloads
      - sonarr_config:/config
    ports:
      - "8989:8989"
    networks:
      - media-network

  media-jackett:
    container_name: media-jackett
    image: lscr.io/linuxserver/jackett:latest
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - jackett_config:/config
    ports:
      - "9117:9117"
    networks:
      - media-network

  media-homarr:
    container_name: media-homarr
    image: ghcr.io/ajnart/homarr:latest
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - homarr_config:/app/config
    ports:
      - "7575:7575"
    networks:
      - media-network

  media-overseerr:
    container_name: media-overseerr
    image: lscr.io/linuxserver/overseerr:latest
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - overseerr_config:/config
    ports:
      - "5055:5055"
    networks:
      - media-network

  media-tautulli:
    container_name: media-tautulli
    image: lscr.io/linuxserver/tautulli:latest
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - tautulli_config:/config
    ports:
      - "8181:8181"
    networks:
      - media-network

  media-jellyfin:
    container_name: media-jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - jellyfin_config:/config
      - /mnt/data/movies:/movies:ro
      - /mnt/data/tv:/tv:ro
      - /mnt/data/downloads:/downloads:ro
    ports:
      - "8096:8096"
    networks:
      - media-network

  media-plex:
    container_name: media-plex
    image: lscr.io/linuxserver/plex:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Edmonton
      - VERSION=docker
    volumes:
      - plex_config:/config
      - /mnt/data/movies:/movies:ro
      - /mnt/data/tv:/tv:ro
      - /mnt/data/downloads:/downloads:ro
    ports:
      - "32400:32400"
    networks:
      - media-network

  media-portainer:
    container_name: media-portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9443:9443" # HTTPS interface
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=America/Edmonton
    networks:
      - media-network

networks:
  media-network:
    driver: bridge

volumes:
  deluge_config:
  radarr_config:
  sonarr_config:
  jackett_config:
  homarr_config:
  overseerr_config:
  tautulli_config:
  jellyfin_config:
  plex_config:
  portainer_data:
