name: media

services:
  media-qbittorrent:
    container_name: media-qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8080
    volumes:
      - /mnt/data/downloads:/downloads
      - /mnt/data/docker/volumes/media_qbittorrent_config:/config
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    networks:
      - media-network

  media-radarr:
    container_name: media-radarr
    image: lscr.io/linuxserver/radarr:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/data/movies:/movies
      - /mnt/data/downloads:/downloads
      - /mnt/data/docker/volumes/media_radarr_config:/config
    ports:
      - "7878:7878"
    networks:
      - media-network

  media-sonarr:
    container_name: media-sonarr
    image: lscr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/data/tv:/tv
      - /mnt/data/downloads:/downloads
      - /mnt/data/docker/volumes/media_sonarr_config:/config
    ports:
      - "8989:8989"
    networks:
      - media-network

  media-jackett:
    container_name: media-jackett
    image: lscr.io/linuxserver/jackett:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/data/docker/volumes/media_jackett_config:/config
    ports:
      - "9117:9117"
    networks:
      - media-network

  # media-homarr:
  #   container_name: media-homarr
  #   image: ghcr.io/ajnart/homarr:latest
  #   restart: unless-stopped
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #   volumes:
  #     - /mnt/data/docker/volumes/media_homarr_config:/app/config
  #   ports:
  #     - "7575:7575"
  #   networks:
  #     - media-network

  media-overseerr:
    container_name: media-overseerr
    image: lscr.io/linuxserver/overseerr:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/data/docker/volumes/media_overseerr_config:/config
    ports:
      - "5055:5055"
    networks:
      - media-network

  # media-tautulli:
  #   container_name: media-tautulli
  #   image: lscr.io/linuxserver/tautulli:latest
  #   restart: unless-stopped
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #   volumes:
  #     - /mnt/data/docker/volumes/media_tautulli_config:/config
  #   ports:
  #     - "8181:8181"
  #   networks:
  #     - media-network

  # media-jellyfin:
  #   container_name: media-jellyfin
  #   image: lscr.io/linuxserver/jellyfin:latest
  #   restart: unless-stopped
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #   volumes:
  #     - /mnt/data/docker/volumes/media_jellyfin_config:/config
  #     - /mnt/data/movies:/movies:ro
  #     - /mnt/data/tv:/tv:ro
  #     - /mnt/data/downloads:/downloads:ro
  #   ports:
  #     - "8096:8096"
  #   networks:
  #     - media-network

  media-plex:
    container_name: media-plex
    image: lscr.io/linuxserver/plex:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=44
      - TZ=America/Edmonton
      - VERSION=docker
      - NVIDIA_VISIBLE_DEVICES=none
      - NVIDIA_DRIVER_CAPABILITIES=none

    volumes:
      - /mnt/data/docker/volumes/media_plex_config:/config
      - /mnt/data/movies:/movies
      - /mnt/data/tv:/tv
    ports:
      - "32400:32400"
    networks:
      - media-network
    devices:
      - /dev/dri:/dev/dri

  media-portainer:
    container_name: media-portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    environment:
      - TZ=America/Edmonton
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /mnt/data/docker/volumes/media_portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - media-network

  media-bazarr:
    container_name: media-bazarr
    image: lscr.io/linuxserver/bazarr:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/data/docker/volumes/media_bazarr_config:/config
      - /mnt/data/movies:/movies
      - /mnt/data/tv:/tv
    ports:
      - "6767:6767"
    networks:
      - media-network

  media-nginx:
    container_name: media-nginx
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - /mnt/data/docker/volumes/media_nginx_config:/etc/nginx
      - /mnt/data/docker/volumes/media_nginx_ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    networks:
      - media-network

  media-tdarr-server:
    container_name: media-tdarr-server
    image: ghcr.io/haveagitgat/tdarr:latest
    ports:
      - "8265:8265"
    environment:
      - serverIP=0.0.0.0
      - serverPort=8265
      - TZ=America/Edmonton
      - PUID=1000
      - PGID=44
    volumes:
      - /mnt/data/docker/volumes/media_tdarr_server_config:/config
    networks:
      - media-network
    restart: unless-stopped

media-tdarr-node:
  container_name: media-tdarr-node
  image: ghcr.io/haveagitgat/tdarr_node:latest
  ports:
    - "8266:8266"
  environment:
    - nodeID=tdarr-node-1
    - nodeName=tdarr-node
    - serverIP=192.168.1.160
    - serverPort=8265
    - nodeIP=0.0.0.0
    - nodePort=8266
    - TZ=America/Edmonton
    - PUID=1000
    - PGID=44
  volumes:
    - /mnt/data/movies:/movies
    - /mnt/data/tv:/tv
    - /mnt/data/docker/volumes/media_tdarr_node_config:/config
  devices:
    - /dev/dri:/dev/dri
  networks:
    - media-network
  restart: unless-stopped


networks:
  media-network:
    driver: bridge

volumes:
  media_qbittorrent_config:
  media_radarr_config:
  media_sonarr_config:
  media_jackett_config:
  media_homarr_config:
  media_overseerr_config:
  media_tautulli_config:
  media_jellyfin_config:
  media_plex_config:
  media_portainer_data:
  media_bazarr_config:
  media_tdarr_server_config:
  media_tdarr_node_config:
  media_nginx_config:
  media_nginx_ssl:
